import StyledComponentsRegistry from '@/components/ui/antd/AntdRegistry'
import '@/styles/globals.css'
import { GeistMono } from 'geist/font/mono'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${GeistMono.variable}`}>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <div className="w-full h-full">{children}</div>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
