import StyledComponentsRegistry from '@/components/ui/antd/AntdRegistry'
import '@/styles/globals.css'

import { GeistMono } from 'geist/font/mono'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

// 测试平行路由（Parallel Routes）

type Props = {
  children: React.ReactNode
}

export default function RootLayout({ children, auth }: Props) {
  return (
    <html lang="en" className={`${GeistMono.variable}`}>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <div className="w-full h-full">
            <div className="px-8 container mx-auto py-6 demo">
              <div className="flex justify-between items-center py-2 border-b border-dashed">
                <h1 className="  text-14px font-500 ">Root Layout 🚀</h1>
              </div>
              <div className="py-6">{children}</div>
            </div>
          </div>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
